### ISSUE TITLE
VirusTotal warnings

### ISSUE THREAD

**Issue by elsaco** [liz3/ledit#3]
After downloading `ledit` from your release repo and scan it, Cynet at VirusTotal flagged it as malicious. I've cloned and built on Windows 10, submit again to VirusTotal, and there are two warnings now. Is it safe to use your editor on Windows?

Sample VT result of local build:

![ledit_virustotal_warning](https://user-images.githubusercontent.com/3933920/155432727-7dabfc2c-8275-42f1-b493-08d831447bcb.png)

**Comment by dabaer** [comment]
The source looks innocuous enough, though I don't know C very well. Can't really say for the pre-built binaries, but you could always build it from source

**Comment by JeDaYoshi** [comment]
Yeah, you can always build it from source. I've never heard of Cynet, but I'm certainly confused as of why Microsoft is detecting it as a trojan. It's for sure a false-positive, though.

**Comment by liz3** [comment]
bruh, if you start with suspecting this as a malware....
It might be because the exe isnt signed but no this is not malware and does not include any actions requiring root, neither does it have ANY network connection.

The only points it touches the OS are: reading/writing files, listing directories for autocomplete, registering a openGL context/window and spawning "git" to determine a branch name.

**Comment by JeDaYoshi** [comment]
Shouldn't this be closed as a non-issue? We can't ask everyone to be happy about the executable.
At worst if Windows Defender were to scream about it, that'd be a real issue - but you could always submit the executable as a false-positive for Microsoft to fix it.
